name: Build Release APK

on:
  workflow_dispatch:
    inputs:
      releaseName:
        description: 'Release name'
        required: false
        default: 'release'
jobs:
  build-release:
    runs-on: ubuntu-latest
    env:
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      API_KEY: ${{ secrets.API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > ./keystore.jks
          ls -l keystore.jks

      - name: Create keystore.properties
        run: |
          cat > app/keystore.properties <<EOF
          storeFile=${{ github.workspace }}/keystore.jks
          storePassword=${{ secrets.KEYSTORE_PASSWORD }}
          keyAlias=${{ secrets.KEY_ALIAS }}
          keyPassword=${{ secrets.KEY_PASSWORD }}
          EOF
          echo "Created keystore.properties"

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build Release AAB and APK
        run: |
          ./gradlew clean assembleRelease -PMAPS_API_KEY=${{ secrets.MAPS_API_KEY }} -PAPI_BASE_URL=${{ secrets.API_BASE_URL }} -PAPI_KEY=${{ secrets.API_KEY }} --no-daemon

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FindMyPath-release-artifacts
          path: |
            app/build/outputs/**/*.apk
            app/build/outputs/**/*.aab
